# Generated by Django 4.1 on 2022-10-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_status_article_is_draft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='subtitle',
        ),
    ]
